### ISSUE TITLE
DynamoDB to opensource

### ISSUE THREAD

**Issue by im-bravo** [aws/aws-database-encryption-sdk-dynamodb-java#247]
Hi, AWS
We were looking for a great document-based database. And we plan to deploy this database using a hybrid cloud and implement asynchronous replication for data redundancy. I know that DynamoDB is a great document-based database and is easy to use on the AWS platform.
But unfortunately I can't deploy it on my private cloud.
Does DynamoDB have open source plans?

**Comment by alebastrov** [comment]
you have to move to AWS private cloud in order to use all benefits from AWS products. DynamoDB is not alone, you can use any alternative on your cloud (Apache Cassandra or MongoDB for instance)

**Comment by justplaz** [comment]
Hi, thanks for reaching out! 

This repository is for the AWS Database Encryption SDK (DB-ESDK) for DynamoDB in Java, which is a client-side library for DynamoDB. We do not work on DynamoDB itself, so we can't answer that question. You might want try asking [AWS re:Post](https://repost.aws/).
