### ISSUE TITLE
Question about running the example

### ISSUE THREAD

**Issue by motica1** [aws/aws-database-encryption-sdk-dynamodb-java#300]
Hey AWS Team,

I am running the example `Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/enhanced/EnhancedPutGetExample.java ` results into `Generator keyring failed to generate plaintext data key` error.  Any pointers to what might be going wrong? 
I have ensured that i have access to the DDB table that I am passing as CLI args.

**Comment by josecorella** [comment]
Hello @motica1,
This example uses an AWS KMS Key that you supply through [CLI args](https://github.com/aws/aws-database-encryption-sdk-dynamodb-java/blob/main/Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/enhanced/EnhancedPutGetExample.java#L162). In order to successfully run the example make sure you have the correct AWS KMS permissions on the key and that you have the correct creds in your environment. For this example you will need at least `KMS:GenerateDataKey` and `KMS:Decrypt`.
Please let us know if that fixes your issue.

AWS Crypto Tools

**Comment by motica1** [comment]
Thanks for the suggestion @josecorella. I tried adding the permissions but still the same error. 
For more context,  I am using [local-stack](https://github.com/localstack/localstack) to run some integration tests with [Database encryption client](https://github.com/aws/aws-database-encryption-sdk-dynamodb-java/tree/main) and KMS. Here is how i am creating my KMS key in local stack 

```
KmsClient kmsClient = KmsClient.builder().endpointOverride(urlOverride.get()).build();
CreateKeyResponse response = kmsClient.createKey();
log.info("key response: {}", response);
clientEncryptionKeyArn = response.keyMetadata().arn();

String policy =
        "\"{\\n  \\\"Version\\\" : \\\"2012-10-17\\\",\\n  \\\"Statement\\\" : [ {\\n    \\\"Sid\\\" : \\\"Enable IAM User Permissions for root\\\",\\n    \\\"Effect\\\" : \\\"Allow\\\",\\n    \\\"Principal\\\" : {\\n      \\\"AWS\\\" : \\\"arn:aws:iam::000000000000:root\\\"\\n    },\\n    \\\"Action\\\" : [ \\\"kms:Update*\\\", \\\"kms:ScheduleKeyDeletion\\\", \\\"kms:Revoke*\\\", \\\"kms:Put*\\\", \\\"kms:List*\\\", \\\"kms:Get*\\\", \\\"kms:Enable*\\\", \\\"kms:Disable*\\\", \\\"kms:Describe*\\\", \\\"kms:Delete*\\\", \\\"kms:Create*\\\", \\\"kms:CancelKeyDeletion\\\" ],\\n    \\\"Resource\\\" : \\\"*\\\"\\n  }, {\\n    \\\"Sid\\\" : \\\"AllowPIIServiceRoleUseOfTheCMK\\\",\\n    \\\"Effect\\\" : \\\"Allow\\\",\\n    \\\"Principal\\\" : {\\n      \\\"AWS\\\" : \\\"arn:aws:iam::000000000000:root\\\"\\n    },\\n    \\\"Action\\\" : [ \\\"kms:UpdateAlias\\\", \\\"kms:Sign\\\", \\\"kms:List*\\\", \\\"kms:Get*\\\", \\\"kms:GenerateDataKey\\\", \\\"kms:Encrypt\\\", \\\"kms:Describe*\\\", \\\"kms:Decrypt\\\", \\\"kms:CreateAlias\\\" ],\\n    \\\"Resource\\\" : \\\"*\\\"\\n  }, {\\n    \\\"Sid\\\" : \\\"EnableIAMRolePermissions\\\",\\n    \\\"Effect\\\" : \\\"Allow\\\",\\n    \\\"Principal\\\" : {\\n      \\\"AWS\\\" : \\\"arn:aws:iam::000000000000:root\\\"\\n    },\\n    \\\"Action\\\" : [ \\\"kms:Update*\\\", \\\"kms:Revoke*\\\", \\\"kms:Disable*\\\", \\\"kms:Delete*\\\" ],\\n    \\\"Resource\\\" : \\\"*\\\"\\n  } ]\\n}\"\n";
    kmsClient.putKeyPolicy(
        PutKeyPolicyRequest.builder()
            .keyId(clientEncryptionKeyArn)
            .policy(policy)
            .policyName("default")
            .build());
```

`urlOverride.get()` is pointing to my local stack instance.

**Comment by motica1** [comment]
this worked! thank you :)
