### ISSUE TITLE
Clarifying question - For Hierarchical key ring, the application needs to know about all the tenants before hand, is that assumption correct?

### ISSUE THREAD

**Issue by motica1** [aws/aws-database-encryption-sdk-dynamodb-java#369]
Hey Team, 

I am considering to use the Hierarchical Key ring for my multi-tenant dynamodb table to separately encrypt/ decrypt each tenants sensitive data, can you help me clarify the following question please?
All the tenants that the dynamodb table is going to serve need to be known first, I am wondering if there is a best practice around onboarding new tenants sharing the same dynamodb table and still allowing usage of per tenant `branch` keys while using  Hierarchical key ring.

**Comment by ajewellamz** [comment]
@motica1,

New tenants can be added as needed over time.

There is a section on "Using the Hierarchical keyring with multitenant databases" here :
https://docs.aws.amazon.com/database-encryption-sdk/latest/devguide/use-hierarchical-keyring.html#multitenant-hierarchical-keyrings

The gist of it all is that you provide a function that takes the partition and sort attributes of an item, and returns the appropriate Branch Key ID for that item.

At the moment, multi-tenant is somewhat hard to use. We are working on a better multi-tenant story, so you may want to wait, but we do not have firm date.
